name: Publish Storybook to Chromatic

# See: https://www.chromatic.com/docs/setup-turbosnap/#github-pull_request-triggers
on:
    workflow_dispatch:
    # Other Khan Academy repositories use this trigger for the chromaui/action
    # and it appears to work-ish, so we'll use the same. If it starts to break,
    # review the above URL to see how to fix it.
    pull_request:
    push:
        branches: [main]

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    chromatic:
        name: Publish Storybook to Chromatic
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [20.x]
        steps:
            # chromaui/@action doesn't work with shallow checkouts which is the
            # default for actions/checkout so we need to force it to checkout
            # more stuff.
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0

            - name: Install & cache node_modules
              uses: ./.github/actions/shared-node-cache
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Publish to Chromatic for visual testing
              uses: chromaui/action@f1f9e3277eb1eaa8cba4c6bcebc9809291ee29ea # v15.0.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
                  autoAcceptChanges: "main"
                  onlyStoryFiles: "**/*-regression.stories.tsx"
                  # NOTE: We cannot enable `onlyChanged` because it is
                  # incompatible with `onlyStoryFiles` which we use above.
                  # onlyChanged: true # Enable TurboSnap!
